fullstorydev/fullstory-data-layer-observer

.editorconfig
2 rules, add more as you see fit :)
=> adding a basic editorconfig

README.md
Adding a couple of things to the project README:
1. A disclaimer about the current state of the project
1. A Badge and link to the CircleCI build
=> adding circleci badge and private beta disclaimer

package-lock.json, package.json
I also removed the `pre-commit` npm package
=> fixed all npm audit issues (all low criticality)

docs/operator_convert.md
Adds the convertor operator doc.
=> add convert operator doc

docs/operator_suffix.md
Adds the suffix operator docs.
=> add suffix operator doc

docs/operator_query.md
Add query operator documentation.
=> Add query operator doc

README.md, docs/operator_convert.md, docs/operator_function.md
A few formatting issues I noticed on GH after we published.
=> fix doc formatting issues

README.md
=> Update docs for beta

examples/google-tags-fs/index.html, examples/rules/google-tags-fullstory.json, test/fullstory.spec.ts
I did a find replace on `digitalData` to `dataLayer`.  This follows the naming convention used by Google in tests and docs.
=> rename digitalData to dataLayer

docs/operator_convert.md, src/operators/convert.ts, test/operator-convert.spec.ts
Support converting elements in a list and assigning a converted value to a property if the list only has one element.
=> Add convert support for lists

CHANGELOG.md, package-lock.json, package.json
=> 1.2.0 release

examples/rules/google-tags-fullstory.json, src/selector.ts, test/fullstory.spec.ts, test/selector.spec.ts
=> Fix to address parsing failure with dot properties

CHANGELOG.md, package-lock.json, package.json, src/observer.ts, src/utils/logger.ts, test/observer.spec.ts
=> Fix rule registration timing failures

CHANGELOG.md, package-lock.json, package.json, src/operators/function.ts, src/selector.ts, src/target.ts, src/utils/object.ts
=> globalThis polyfill

.circleci/config.yml
This introduces a build step to CI
=> adding a build step and separating out the test step

CHANGELOG.md, package-lock.json, package.json
=> Update 1.4 documentation

src/utils/logger.ts, test/logger.spec.ts
This PR adds debouncing of LogEvents specifically to the FullStory appender.  I'm seeing some situations where due to older browsers or other reasons, DLO fails processing rules for the same pathology.  Debouncing helps limit seeing multiple events in replay as well as preventing rate limiting for 10 event per second bursts.  To debounce, the LogEvent has to have the same source, message, and reason.  Together those 3 usually mean a total failure rather than one-off timing issue or single rule issue.
=> Add log debouncer for FullStory

CHANGELOG.md, package-lock.json, package.json
=> Add 1.4.2 doc

src/embed/init.ts, src/monitor-shim.ts, src/observer.ts, src/utils/logger.ts, test/observer.spec.ts
Add a bit more error catching to DLO initialization.
Added timing logs for DLO initialization.
=> DLO observation messages

CHANGELOG.md
Forgot the changelog bump for the PR #128.
=> add missing changelog for 1.6.5

CHANGELOG.md, README.md, package-lock.json, package.json
Release notes for when #139 and #137 are merged.
=> 1.8 release notes

docs/operator_suffix.md
=> Fix maxProps typo

package-lock.json, package.json
https://github.com/cowpaths/mn/pull/44773
=> Update rollup to 2.70.1 per Snyk recommendation

CHANGELOG.md, README.md, package-lock.json, package.json
This PR bumps the version number to 2.1.1
=> bump version number

CHANGELOG.md, README.md, package-lock.json, package.json
This PR bumps the version number to 2.1.2
=> bump version to v2.1.2

docs/operator_parse.md, src/operators/index.ts, src/operators/parse.ts, test/operator-parse.spec.ts
This operator will allow us to deal with strings that need to be parsed by some delimiter.  Made sure it would work with adobe's standard encoding.
=> Parse operator

package-lock.json, package.json
Addresses a dev dependency vulnerability: https://security.snyk.io/vuln/SNYK-JS-MOCHA-2863123
=> Update mocha dev dependency

.circleci/config.yml, CHANGELOG.md, README.md, package-lock.json, package.json
Webkit browser test was failing and this playwright bump fixed it ![success](https://emoji.slack-edge.com/T02FE3LFK/success/fece95332fd73b56.png)
~~Also ran `npm audit fix` to clean up some bad build deps.~~
Actually that broke CI so this is only the playwright bump
=> bump build deps
