fullstorydev/fullstory-data-layer-observer

test/ceddl.spec.ts, test/data/CEDDL.ts, test/operator-pick.spec.ts
This implements the various interfaces for CEDDL and creates a couple of instances of it for use during testing.
@van-fs One question: I wrote a test for CEDDL using the pick operator and it is failing. So, I've added a pick operator test that (I think) reproduces the failure in the context of the pick tests. Am I missing something about how the properties option is able to specify that a property at any depth can be picked?
=> Added interfaces for the full CEDDL spec

test/mock.ts, test/vendor.spec.ts, test/vendor/fullstory-recording.ts
Putting this up for comment by @van-fs before going much farther with it. Specifically, it needs a review of the mocking method.
After looking at current mock libs like Sinon (complex) and our needs for mocking FS's recording APIs (simple) I whipped up a basic `MockClass` that (when extended) records calls to any methods on a class for checking during a test.
Take a look at `test/vendor/fullstory-recording.ts` and `test/vendor.spec.ts` to see how we could test that the FS recording API is called (eventually) by the DLO.
=> Mock up a FullStory recording API for use in unit testing

tsconfig.json
Given we're using different editors, I've added a `tsconfig.json` to the project.  This mirrors a lot of what's in our mn packages, and it's more or less common defaults.  We can always modify, but I wanted to get this in before we get much farther along.
=> Add tsconfig to project

test/operator-pick.spec.ts
Two tests are failing.  Patching for now, but we'll swap the PickOperator in favor of the query syntax.
=> Fix pick tests

.circleci/config.yml
This will run `npm test` and `npm audit --audit-level=low` as part of a merge check before merging into master
=> basic ci test and audit runner

package-lock.json, package.json, src/event.ts, src/handler.ts, src/utils/object.ts, test/handler.spec.ts
This PR introduces the `DataHandler` to respond to and process event data using operators:
- Events emitted from future `PropertyListener`s will emit `CustomEvent`s, which will use `DataLayerDetail` to provide metadata from the data layer. Individual `FunctionDetail` and `PropertyDetail` classes further disambiguate the type of event from the data layer.
- The `DataHandler` responds to events and processes based on the data layer `path`.  The `path` is used by the handler to decide if the event data should be processed: event listeners all listen to the same `type` event so something must be used to choose when to run the handler.  The multicast design is provided by the browser - it's not ours.
- There's a `debug` flag specifically in the handler instance. This allows the user to debug …
=> Add DataHandler to process event data

.circleci/config.yml, src/selector.ts, test/logger.spec.ts, test/selector.spec.ts
This will eventually provide the path selection utility methods used to find rule sources and within operators. The goal is to use path selection strings like `digitalData.page.pageInfo.author` or `digitalData.cart.item[-1].quantity` to traverse the Javascript namespace and find specific information.
=> Path selection utility methods.

test/operator-pick.spec.ts
This little PR replaces `bind()` invocations in a handful of test methods with closures using anonymous functions.
Also: testing a PR after renaming the default branch to `main`
=> replacing bind function call with closure

src/handler.ts, test/handler.spec.ts
This PR refactors `DataHandler` to use the new selection syntax.  The test was also updated to have a `before` and `after` to add and remove mock data from global scope.
One point on looking ahead.  The `DataHandler` class currently has to find `target` to support `fireEvent`.  When we add `PropertyListener`s that need should go away.  The handler then only needs to know the `path` and decide if it should kick off handling the data via operators.  It shouldn't need the target object itself.  Firing an event makes more sense in the listener as well.
=> refactor to support select

package.json, src/selector.ts, test/logger.spec.ts, test/operator-pick.spec.ts, test/selector.spec.ts, tsconfig.json
This PR adds the remaining selection syntax: pick, omit, prefix, suffix, filter
In a previous PR we omitted the tests in /test/ when adding tests in /test/mocks/ so I re-added that.
Also fixes the globalThis.console which was being overwritten in other tests.
=> Remaining selection syntax

.eslintrc.json, package-lock.json, package.json
This PR:
- Installs eslint with the airbnb style guide and adds two new npm scripts: `lint` which executes eslint in the `src` and `test` directories and `lint:fix` which does the same but adds the `--fix` argument to automatically fix any linting errors that are automatically fixable
- Installs the `pre-commit` package and executes `lint:fix` in a git pre-commit hook
Right now there are 93 eslint issues that can't be automatically fixed (and about 120 that can). These 93 errors must be fixed manually. 
With the pre-commit hook in place, you'll need use the `-n` (no-verify) argument when committing files while working through the linting issues:
```
git add {whatever}
git commit -n -m "some message"
```
=> adding eslint + git pre-commit hook

src/observer.ts, src/operators/function.ts, src/operators/index.ts, test/observer.spec.ts, test/operator-function.spec.ts
This PR adds the main functionality of DataLayerObserver for static data layers.  The `readOnLoad` property is heavily used in this iteration.  The `FunctionOperator` is a key component since it is used with the `destination` in rules.
=> Adding DataLayerObserver core

src/factory.ts, src/handler.ts, src/observer.ts, src/operator.ts, src/operators/function.ts, src/operators/index.ts, test/handler.spec.ts, test/observer.spec.ts, test/operator-function.spec.ts, test/operator.spec.ts
I took @patrick-fs PR and riffed on it.  I've moved the `Operator` away from an abstract class to a basic interface.
```
export interface Operator {
options: OperatorOptions;
handleData(data: any[]): any[] | null;
validate(): void;
}
```
To make it so that `DataLayerObserver` can deal with arbitrary metadata coming from `DataLayerRule`, an `OperatorFactory` was created.  The factory internalizes the creation of an `Operator` to it versus doing it in the `DataLayerObserver`.  The factory will make for a cleaner separation and way to organize operators we provide.  To support some of the type checking, we'll have to maintain two union typedefs as we build more operators. 
```
export type BuiltinOperator = typeof FunctionOperator | typeof SomeFutureOperator;
export type BuiltinOptions = …
```
=> Refactor to support interfaces versus generics

src/handler.ts, src/observer.ts, test/handler.spec.ts, test/observer.spec.ts
This PR allows end users to configure debug for specific rules.  It also adds more robust testing that rules are printed to console.debug using the mock console.  This supports acceptance criteria in CH119003.
=> Add debug flag in observer

src/factory.ts, src/operators/flatten.ts, src/operators/index.ts, test/operator-flatten.spec.ts
The `FlattenOperator` copies nested properties into a top level object.  This is a required step prior to using APIs such as `FS.setUserVars` or `FS.event`.
=> Add flatten operator

src/factory.ts, src/operators/index.ts, src/operators/suffix.ts, test/operator-suffix.spec.ts
This PR adds the `SuffixOperator`, which is needed for suffixing objects with type information before sending to FullStory.  This will place vendor-specific behavior into core, but suffixing is complex enough that it requires a large amount of code to do so and bolting it on from the outside would be a chore.
Since suffixing is required if using FullStory, the `beforeDestination` option will be used to specify that the `suffix` operator run every time rather than requiring specific reference to suffix in the operator chain.
=> Add  suffix operator

src/factory.ts, src/operator.ts, src/operators/index.ts, src/operators/insert.ts, test/operator-function.spec.ts, test/operator-insert.spec.ts
This PR introduces the `InsertOperator`.  In the prototype, there was a `prepend` operator that added a value to the beginning of a list.  The use case here is adding information to a list of function arguments that are passed to the `destination` function.  So you might add 'Add to Cart' as a literal to FS.event arguments.  Or you might grab the value of `profileID` to be used with FS.identify.  The design was expanded to be more flexible - supporting arbitrary insertion into the list rather than specifically prepending.  The comments in the `InsertOperator` have detail as well.
=> Add insert operator

src/factory.ts, src/operators/index.ts, src/operators/query.ts, test/operator-query.spec.ts
@TrevorFSmith @patrick-fs  While writing the user rules, I had a need to do the following:
```
{
"id": "fs-identify-ceddl-user-allowed",
"description": "send only known CEDDL user properties to FS.identify using the profileID as the FullStory uid",
"source": "digitalData.user.profile[0][(profileInfo.profileID,profileInfo.userName,address.line1,...)]",
"operators": [
{
"name": "flatten"
},
{
"name": "insert",
"select": "profileID"
}
],
"destination": "FS.identify"
}
```
That stretches the ability of the selector syntax.  Do we feel like that is valid syntax?
Alternatively, I was thinking we might have an operator that allows us to perform selection within any step of the operator chain.  It would look something like this:
```
{
"id": "fs-identify-ceddl-user-allowed",
"description": "send …
```
=> Add QueryOperator

src/factory.ts, src/operators/convert.ts, src/operators/index.ts, test/operator-convert.spec.ts
This PR adds a `ConvertOperator` to convert from one type to another.  The use case is that some data layers have string values like `1.99` when this would be better represented as numeric in a destination.  It supports the `cart` object better for CEDDL work.
One design point is that I've taken some precaution to not mutate the underlying object, but this is a sharp edge for operator implementors.  I'll create a story that moves deep copying so it's not the responsibility of the operator.
=> Add convert operator

examples/rules/ceddl-cart-fullstory.json, examples/rules/ceddl-user-fullstory.json, test/fullstory.spec.ts
This PR adds examples for FullStory and CEDDL Cart.  The example JSONs were converted to objects with a `rules` property.  I saw some odd behavior when trying to iterate over the pure list.  Making the examples objects with a `rules` property and a value of an array solved this.  Also added a `getRule` function to make it clearer which rule to test rather than relying on the order in the list.
=> add FullStory CEDDL Cart spec

examples/rules/ceddl-page-fullstory.json, src/operators/convert.ts, test/fullstory.spec.ts, test/operator-convert.spec.ts
This PR adds the CEDDL Page spec.  There is some light conversion of the data into more semantic types useful to FullStory.  I added a `date` type to the `ConvertOperator`.  This will allow us to take a `Date` object converted from a string and send it to FullStory with the `_date` suffix.
=> add FullStory CEDDL Page spec

rollup.config.js
Change the rollup config for the bundle build so it no longer writes properties to the window.
=> Rollup configuration to leave the `window` alone

examples/rules/ceddl-transaction-fullstory.json, test/fullstory.spec.ts
This turned out to be pretty basic.  It simply aligns our "Order Completed" event name seen in documentation as a rule.
There's a stretch goal that we could pursue as a follow on in next iteration.  Normally the Order Completed event carries with it a `products` array.  That in turn fires N "Product Purchased" events.  What we lack in this rule set is the products purchased, and I don't think that's too detrimental.  But a possibility is that we create a `foreach` operator that would execute the remaining operator for each element in the `items` list.  The result would emulate the `Product Purchased` event and be helpful for other use cases where lists of objects are encountered.
=> add ceddl transaction rules

src/selector.ts, test/selector.spec.ts
This adds more comparison features to the selector (currently we only support `=`).  Note this uses `eval`.  Alternatively, I can remove the eval and do a switch on the combinations of operators `<=`, `!=`, `>=`, etc.
=> add more comparisons to selector

src/operators/convert.ts, test/operator-convert.spec.ts
I fixed a bug in how the boolean conversion from a `'true'` or `'false'` was done.
The other scenario encountered was if a rule wanted to always try to convert a value to a real or int.  If the value was null, we'd actually leave it as is but console.error that we couldn't convert.  This can get noisy and gives the appearance of an error when none really exists.  So this fix also assumes that a null being converted to an int/real yields a zero value.  It's worth thinking through if there are any undesirable side-effects.  A similar question is whether other type conversion of null (e.g. `string`) should provide a default value such as the empty string.
=> bug fix for boolean and nulls

src/handler.ts, src/operators/function.ts, test/handler.spec.ts
This PR adds additional debug, which helps calculate the number of properties and data sizes.  A bug was also found related to the function operator where it was not wrapping the returned data in a list.  (Every operator should return a list.)
=> add debug stats

src/embed/init.ts, src/observer.ts, src/utils/logger.ts, test/observer.spec.ts
Looks like we had support for the custom log appender but it was not available to declare as an option to `init`.  This PR allows mounting `FS.event` as an appender so that we can pipe logs/errors to FullStory.  Usage would be similar to:
```
window['_dlo_appender'] = {
log: ({ level: level_int, message: message_str, datalayer: datalayer_str }) => {
const FS = window[window['_fs_namespace']];
console.log({ level_int, message_str, datalayer_str })
if (FS) FS.event('Data Layer Observer', { level_int, message_str, datalayer_str }, 'dataLayerObserver')
}
};
```
=> add FS.event appender

examples/ceddl-fs/index.html, examples/index.html, package-lock.json, package.json, src/operators/convert.ts, test/web-embed-lab/.gitignore, test/web-embed-lab/README.md, test/web-embed-lab/auto-formulate.conf.json, test/web-embed-lab/auto-formulate.sh, test/web-embed-lab/ngrok-auto-formulate-config.yml.example, test/web-embed-lab/run-tests.sh, test/web-embed-lab/runner.conf.json, test/web-embed-lab/test-probes/dom-shape/test.js, test/web-embed-lab/test-probes/exceptions/test.js, test/web-embed-lab/test-probes/fs-backend/test.js, test/web-embed-lab/test-probes/heap/test.js, test/web-embed-lab/test-probes/performance/test.js, test/web-embed-lab/test-probes/selector-count/test.js, test/web-embed-lab/test-probes/text-equals/test.js
This PR sets up two new npm run targets: `test:wel-auto-formulate` and `test:wel-runner`
`test:wel-auto-formulate` uses the Web Embed Lab to test the DLO in the context of two example pages, one which is the most basic setup (`examples/basic-embed`) and a new one that tests CEDDL to FullStory rules (`examples/ceddl-fs`).
I'll add docs about setup once I've heard from @van-fs about this general direction, but to run the tests the user needs  to set up two files (both in the `test/web-embed-lab/` dir) that configure the WEL with ngrok and Browserstack keys. Basically, the user has to copy and fill out the *.example files in that dir (removing the `.example` extension).
=> Add Web Embed Lab Testing

package-lock.json, package.json, src/event.ts, src/handler.ts, src/monitor-shim.ts, src/monitor.ts, src/observer.ts, src/selector.ts, src/target.ts, test/handler.spec.ts, test/observer.spec.ts, test/selector.spec.ts, test/shim-monitor.spec.ts, test/utils/mocha.ts
This PR adds the concept of a "monitor" to watch for changes on a property.  I used "monitor" so it wouldn't be confused with implementation, which uses EventListeners.
- The shimming technique applies to all properties in a given object, which would be the result of a selector having been run.  You can optionally not shim `monitor=false` in a rule if you only wanted to `readOnLoad`.
- The specs use NPM deepcopy since I had a few issues with test pollution.
- I had to add `monitor: false` to all our previous observer.spec rules since the default behavior was true and that had side-effects.  That and a lint:fix caused more changes than normal.
- I added some selector.spec tests because I'm explicitly relying on dot notation select to return a reference to an object and not a copy.
=> Add shim property change listener

src/observer.ts, src/utils/logger.ts, test/logger.spec.ts, test/observer.spec.ts
I refactor the logger a bit to do two things:
1. Allow a more generic way to provide context.  Previously, important identifiers like rule ID, selector, path, etc got put into the message because that was all we had.  This is problematic because when there are multiple identifiers, the message can be rather long.  Another issue is that we sometimes use selector, source, and path interchangeably.  Now that these are better defined from the shim PR, we can send these to FullStory as discrete name:value pairs in a custom payload.
2. Add an option to configure FullStory as the log appender.  This was possible before, but the code was part of the window expando.  Now the code is in Logger, and you'll do `window['_dlo_appender'] = 'fullstory'`.  We'll still accept a custom `LogAppender` but …
=> Refactor logger for message cleanup

src/factory.ts, src/handler.ts, src/operators/fan-out.ts, src/operators/index.ts, test/operator-fan-out.spec.ts
The fan out operator allows us to specify a set of properties on a source that each should have the remaining rules applied to them. It needs a special case in the Handler so it's a bit different than the other operators.
=> Add the fan out operator.

src/operators/fan-out.ts, test/operator-fan-out.spec.ts
If the rule writer leaves out the `properties` parameter of the fan out operator then for an array it fans out every item in the array and for a non-array object it fans out all values of the object.
=> The fan out operator properties parameter is now optional.

src/event.ts, src/handler.ts, src/monitor-factory.ts, src/monitor-shim.ts, src/monitor.ts, src/observer.ts, src/target.ts, test/observer.spec.ts, test/shim-monitor.spec.ts, test/utils/mocha.ts
Initial function shim implementation added.  I'm going to revisit and cleanup.  The `DataLayerTarget` and `DataLayerObserver.addMonitor` are a bit messy.  You have to walk back up to the parent to get a reference to it and the `property` (i.e. function).
=> Add function shim

examples/google-tags-fs/index.html, examples/index.html, examples/rules/google-tags-fullstory.json, package.json, src/monitor-factory.ts, src/observer.ts, src/target.ts, test/fullstory.spec.ts, test/mocks/google-tags.ts, test/operator-fan-out.spec.ts
In addition to the rules, tests, and example page for google tags, this PR has a couple of tweaks to how we handle rules that are both read-on-load and monitor of array sources.
The monitor also checks that a property is configurable before trying to monitor it.
=> Rules to send Google tags to Fullstory

CHANGELOG.md, README.md, docs/operator_fan-out.md, docs/operator_rename.md, package-lock.json, package.json
Updated docs to reflect V1.1.0.  @TrevorFSmith can you check the fan-out doc?  I'm trying it in an integration test, and this is the debug output:
```
dataLayer[0].ecommerce.promoView.promotions handleData entry
[{"id":"1004-Blueberries123321","name":"Fruits","creative":"Blueberries123321","position":"Feature"}] 1.1.0.js:1:18535
dataLayer[0].ecommerce.promoView.promotions handleData exit
[] 1.1.0.js:1:18535
dataLayer[0].ecommerce.promoView.promotions handleData entry
[{"id":"1001-Strawberries222333","name":"Fruits","creative":"Strawberries222333","position":"Sub1"}] 1.1.0.js:1:18535
dataLayer[0].ecommerce.promoView.promotions handleData exit
[]
```
It doesn't seem like it executes the handler chain.  Here's the data layer 
```html
<script>
dataLayer = [
{
event: 'impressions_loaded', …
```
=> v1.1.0 doc changes

examples/basic-embed/index.html, test/web-embed-lab/auto-formulate.conf.json, test/web-embed-lab/runner.conf.json, test/web-embed-lab/sites/basics/index.html, test/web-embed-lab/test-probes/dlo-rules/test.js
I created a [WEL test probe](https://github.com/fullstorydev/web-embed-lab/blob/master/docs/TEST_PROBE_API.md) and a testing page that work together to ensure that the rules ran, that the right number of results were created, and that the results have expected parameters.
In the future we can flesh this out to test the intricacies of each operator but this satisfies the task which is to make sure that the DLO successfully evaluates rules.
=> WEL rule probe and separate test "site" 

examples/basic-embed/index.html, src/monitor.ts, src/observer.ts, src/target.ts, test/utils/mocha.ts
Make the magical monitoring of arrays include `unshift` in addition to `push`.
This is the first time that a single input rule can result in multiple running rules. Instead of converting a rule that watches an array into a rule that watches that array's `push` we now do that and *in addition* add a rule to watch `unshift`.
=> Magical unshift

examples/google-tags-fs/index.html, examples/rules/google-tags-fullstory.json, test/fullstory.spec.ts, test/mocks/google-tags.ts
Added rules (with example page and tests) that hand the [Google Tag eCommerce](https://developers.google.com/tag-manager/enhanced-ecommerce) data layer objects to Fullstory.
=> Add Google Tag eCommerce rules

docs/operator_insert.md, examples/rules/ceddl-fullstory.json, src/operators/insert.ts, test/fullstory.spec.ts, test/mocks/CEDDL.ts, test/operator-insert.spec.ts
Looks like I never had an `event` rule - probably because we didn't have fan-out at the time.  Adding a rule for it.  
The spec says that the `eventName` property must be present; however, I've already found a data layer that is not following that guidance.  To maximize using the real event's name with non-compliant data layers, I added a `defaultValue` fallback for the `insert` operator.
=> Add CEDDL Event Rule and Insert defaultValue

CHANGELOG.md, package-lock.json, package.json
Updated changelog and package to reflect the new `defaultValue` option for insert.  This feature will be used in the next version of souq.
=> v1.3.0 release updates

CHANGELOG.md, package-lock.json, package.json, src/embed/init.ts, src/factory.ts, src/handler.ts, src/monitor-shim.ts, src/monitor.ts, src/observer.ts, src/operators/convert.ts, src/operators/function.ts, src/operators/insert.ts, src/selector.ts, src/target.ts, src/utils/logger.ts, test/logger.spec.ts
This closes #56 and cleans up/bubbles up a lot of the error messages.  I took the approach:
- If DLO is calling a `log` event, a shorter `LogMessageType` was used (e.g. `Empty Event`).  It's a mix of trying to re-use error messages and mimic what's done in [FS API error kinds](https://help.fullstory.com/hc/en-us/articles/360020624394#API%20Error%20Kinds).
- The above lacks a bit of clarity, and when an `Error` is constructed, you can use `Logger.format` and `LogMessage` to create a more descriptive message.  Anything in `err.message` gets put into the context object as `reason_str: <message>`.  This was used heavily in `selector.ts` to be more granular with parsing related errors.
=> Error message cleanup

package.json, src/embed/init.ts
A TS compile-time error was introduced in my last PR to clean up error messages.  Unfortunately, it looks like we don't tsc in pre-commit.  This PR address the actual bug.  @patrick-fs, thoughts on simply adding `tsc` to the `pre-commit` hook?  Would the solution be that easy?
=> Fix build error

README.md, examples/rules/google-tags-fullstory.json, src/selector.ts, test/selector.spec.ts
This PR adds a bit more all-purpose support to Google Analytics.  While we have Enhanced Ecommerce rules, the basic Google Analytics usage in `ga.js`, `analytics.js`, and `gtg.js` needs to also be supported.  To that end, the rules were updated and a new comparison syntax to support "does not start with" was added.  This allows us to ignore noisy GA events like `gtm.dom` and `gtm.js`.
Google's newer `gtg.js` actually behaves a little differently.  Rather than inserting an object into the data layer, it adds `Arguments`.  This required a bit of creativity to leverage our existing operators.  It's worth documenting as an advanced operator tutorial, but I'll get to that at a later date.  I want to PR the support so that we can add GA as a souq ruleset.
=> Add google analytics all purpose rule support

examples/rules/tealium-fullstory.json, src/observer.ts, test/fullstory.spec.ts, test/monitor-factory.spec.ts, test/observer.spec.ts
This PR limits when we add monitors to properties in a data layer.  Previously, we added monitors on all properties in the data layer.  The result was that a property change would fire and the data handler ran the appropriate selector to return the desired data.  I _think_ monitoring all properties may have just been a convenience approach rather than anything intentional.  @TrevorFSmith Do you recall any specific situation why monitoring all props was necessary?
When a data layer has ALOT of properties, the current implementation has the side effect that we are over eventing.  For example, the Tealium default rule is `utag.data[?(tealium_event)]`.  This means that we're monitoring all properties in `utag.data`, but the default rule's query operator has us only getting a subset of this …
=> Limit monitoring scope

CHANGELOG.md, docs/operator_suffix.md, package-lock.json, package.json, src/operators/suffix.ts, test/operator-suffix.spec.ts
This PR skews suffixing numeric values as `real`.  For example, whole numbers such as `200.00` are considered as a `real` rather than `int`.  The issue is that a property related to price might be interpreted as an `int` because it is a whole number but should ideally be a `real` for consistency purposes.  Doing this groups it with other price values such as `200.01` that already exist.
=> Normalize numbers as real

CHANGELOG.md, README.md, package-lock.json, package.json, src/embed/init.ts, src/observer.ts
We've always had the ability to set and leverage `LogLevel` to control debug messages.  This PR exposes that ability as a config option.  External configurability allows souq to turn off logging if desired.
=> Expose logging level config option

README.md, examples/rules/google-tags-fullstory.json, src/selector.ts, test/selector.spec.ts
The Google Enhanced Ecommerce ruleset and Event Measurement rulesets are very similar.  When used together, I think there a definite possibility we might record an event for each if an Enhanced Ecommerce hit fires.  The reason is that EM is essentially a superset of EC.  To better ignore EC events when also using the EM ruleset, I added a check that allows us to see if a property is/is not undefined.  This way we can check if `ecommerce` is defined in the event and if so, ignore it assuming the EC ruleset is also deployed.
=> Ability to compare undefined

src/selector.ts, test/selector.spec.ts
While doing #109 I happened to notice there was no `!=` for strings in `select`.  I also saw line 198 in the test looked like a copy/paste.  Wondering if `!=` has gone unnoticed as a bug.  @TrevorFSmith , does the previous line 399 jog any memory of why it doesn't conform to all the other if blocks.  This is the only one that used a `!=` comparison.  Feels out of place.
=> String not equal bug

CHANGELOG.md, README.md, package-lock.json, package.json, src/selector.ts, test/fullstory.spec.ts, test/selector.spec.ts
I found an issue with #109.  Originally the goal allowed you to check that a non-existent property is `undefined`.  There's, however, the possibility that you also need to check that a defined property is `undefined`.  I bumped the versions to do a new deploy too.
I think there's also some found work in the selector code related to error checking which comparison operators are valid.  For example, you could compare using `!^` with a number, which I *think* falls through the switch statements and passes.  I'll add a card to track, but I bring it up because the new `undefined` behavior expects you to use `!=` and `=` but doesn't enforce it.
=> add fix for undefined comparison

CHANGELOG.md, package-lock.json, package.json, src/operators/convert.ts, test/operator-convert.spec.ts
Quick fix for an issue found with `convert` operator and spaces in the property list.
=> Convert when spaces are provided

CHANGELOG.md, README.md, package-lock.json, package.json, src/observer.ts, test/observer.spec.ts
This PR adds checks on `push` and `unshift` and closes #106.  Older browsers fail to have these functions.
=> Array push and unshift checks

CHANGELOG.md, README.md, docs/operator_convert.md, examples/rules/tealium-fullstory.json, package-lock.json, package.json, src/operators/convert.ts, test/fullstory.spec.ts, test/operator-convert.spec.ts, test/utils/mocha.ts
This PR addresses a few issues seen with Tealium users.
- The sample rule needs frequent updates to convert strings to numbers
- `order_` information was not included in the original sample
- The `convert` operator could do a better job of intelligently converting to numbers
An `enumerate` option was added to `convert`.  The intent is that if specified, `convert` will try to automatically convert strings to numbers.  There was a fair amount of cleanup needed in convert, and I broke the handler into stages:
- Enumerate any strings if desired
- Convert any additional properties specifically
- Reduce any single item arrays to a single value if needed
Two test utility methods `expectValid` and `expectInvalid` were added to make the validate tests more legible.  (We should refactor other tests …
=> Add enumerate feature to convert operator

src/utils/logger.ts, test/logger.spec.ts
I have an in-flight PR that adds `dlo` as the source param to souq rules.  I'm changing the `FullStoryAppender`'s source name to be `dlo_log` to better differentiate between "real" data layer events and log-generated events.
=> Change logger source name

CHANGELOG.md, README.md, package-lock.json, package.json, src/operators/suffix.ts, test/operator-suffix.spec.ts
This PR fixes a bug where an `FS` API includes the `source` param.  Previously, the suffix operator expected that the object to suffix was last in the list of args.  Adding the `source` param changes that assumption. The suffix operator succeeds but sends malformed data to FullStory.  This results in FullStory rejecting the event with [Expected Atom](https://help.fullstory.com/hc/en-us/articles/360020624394-Troubleshooting-Recording-Client-API-FS-event-FS-setUserVars-and-FS-identify-errors#expectedAtom) errors.
=> add suffix bug fix and bump version

src/embed/init.ts
In embed, the Logger needs to be initialized with the custom appended (`fullstory`) so that stats and early failures are correctly appended.
=> Initialize the logger early in the embed script 

CHANGELOG.md, README.md, package-lock.json, package.json, src/operator.ts, src/operators/convert.ts, src/operators/flatten.ts, src/operators/insert.ts, src/operators/rename.ts, src/operators/suffix.ts, test/operator-convert.spec.ts, test/operator-flatten.spec.ts, test/operator-rename.spec.ts, test/operator-suffix.spec.ts
This PR fixes an issue where the flatten operator unintentionally updates the data layer.  The issue was due to assignment of new data to a shallow reference.  Flatten is an older operator, and it did not have the convention seen in more recent operators:
```
const clone = data.slice();
clone.splice(this.index, 1, flattened);
return clone;
``` 
I added additional test cases to the `flatten.spec.ts` and carried over the same test to two other specs (`convert.spec.ts` and `rename.spec.ts`) just to confirm they also did not have a similar bug.  No problems were found with these operators, and the convert operator has numerous checks for data layer side effects.
=> Fix data layer side effect from flatten operator

CHANGELOG.md, README.md, package-lock.json, package.json, src/handler.ts
Normally, a data layer event where the observed changed was `undefined` triggered a warning log message.  This was designed to signal that a possible DLO bug was present.  It appears that there may be data layers where `undefined` is assigned to an observed property as a way to "clear" variables in the data layer.  This may be done at a high volume in which case, `warn` is undesirable because it could cause rate limiting.  This PR moves the log level from `warn` to `debug` to allow this scenario while still retaining the ability to know when an undefined assignment is occurring.
=> Undefined empty events

README.md, docs/operator_suffix.md, package-lock.json, package.json, src/operators/suffix.ts, test/operator-suffix.spec.ts
The new page vars API was not allowing us to set the `pageName` correctly because we by default auto-suffix all properties.  When the property was set to `pageName_str`, FullStory did not correctly infer the page name because it is specifically looking for `pageName`.  Adjustments were made to `displayName` and `email` as well.
=> Suffix Corrections

CHANGELOG.md, README.md, package-lock.json, package.json, src/observer.ts, src/operators/convert.ts, test/observer.spec.ts, test/operator-convert.spec.ts
This feature has been on the backlog for a while re: #108 .  It's become more clear that there's a need for multiple, required operators to support FullStory use cases: suffixing, adding the `source` param, and now auto-converting strings to numbers using the `enumerate: true` feature of the `convert` function.
So what I've done is updated the `beforeDestination` feature to take a list of always-executed operators prior to calling the `destination` function.  This change will support more concise configuration such as `{window['_dlo_beforeDestination'] = [{ name: 'convert', enumerate: true }, { name: 'suffix' },  { name: 'insert', value: 'dlo', index: -1 }]`.
For completeness, it's worth doing some level of performance analysis to see what an "always on" auto-conversion yields.  I'll do …
=> Allow more than one operator for beforeDestination

tsconfig.json
Internal build warns because comments exist in JSON.  Removing comments.
=> Remove tsconfig.json comments

CHANGELOG.md, README.md, package-lock.json, package.json, src/observer.ts
I've seen an uptick in error logs that indicate the `name` property is missing from operator options.  I can't understand how that's happening so I've added additional logging to print the raw operator that gets passed into configuration.
=> Increased logging visibility

CHANGELOG.md, README.md, package-lock.json, package.json, src/observer.ts, test/observer.spec.ts
Looks like the logic for overriding the global config for `readOnLoad` is incorrect.  If DLO is globally configured as `readOnLoad:true`, it's not possible to make a rule that had `readOnLoad:false`.  This now checks if a rule has `readOnLoad` defined and sets the behavior accordingly.
=> Fix read on load for rules

src/monitor-shim.ts, test/shim-monitor.spec.ts
Some object-based data layers appear to be re-assigning the same value to properties very frequently.  Conceptually that is problematic because it produces a change event that triggers the operator chain, which would send an event to the destination.  This scenario has been less noticed because property setters are debounced higher in the call stack by the `DataHandler`.  So a no-op, same-value reassignment occurs within the debounce window of a different property's assignment of a different value.  When the debounce time limit is reached, the two properties get collected, which looks like a valid change event because one property's did change.  As the list of properties under observation in the object grows, it appears the incidence of these "same value" assignments can occur.  For super …
=> Guard emitting the same value

src/operators/convert.ts, test/operator-convert.spec.ts
Historically the `ConvertOperator` allowed you (end-user) to specify what to convert.  The default behavior of `convert` on an empty string to a `real` is that the resulting value is `0`.  After introducing `enumerate` where `convert` tries to auto-convert for convenience, this has what appears to be an unwanted side effect.  If the properties selected from an object in the data layer are broad (e.g. all eVars), many times those get "cleared" by setting the existing value to empty string.  DLO then converts it to a 0, which is probably unexpected and has the second drawback of creating `eVarN_str` and `eVarN_real` in custom event properties.  So it feels best to just leave empty strings as-is for enumeration specifically.
Obscure technical detail: while the code change now checks if a …
=> Enumerate shoudn't convert empty strings

src/handler.ts, src/observer.ts, test/handler.spec.ts, test/observer.spec.ts, test/rules-tealium-fullstory.spec.ts
Recently, I've found that very active data layers (object-based in particular) can over-emit events.  I found a few areas of improvement:
- adding a config option to set the debounce time allowing some rules more time for the data layer to cool down
- moving the `this.timeoutId = null;` to unset the debounce flag; I saw that for a really really data layer I saw code that had its timeout cleared still executed.  Maybe some issues with the scope?  Open to theories on this change.
=> Add configurable debounce time

CHANGELOG.md, docs/operator_suffix.md, package-lock.json, package.json, src/operators/suffix.ts, test/operator-suffix.spec.ts
There was a Clubhouse ticket where a customer had long delays on their site.  This was tracked back to a super-size (120MB) object being added to the data layer.  The object had a reference to the React app, which is why it was so big.  In order to guard against wayward objects in the data layer either impacting site performance or simply overrunning our cardinality quota on `FS.event`, I've put a cap on the `suffix` operator's total property count at `100`.  This was done through an informed analysis of DLO events and is not arbitrary.
The rationale for doing this in the `suffix` operator is because it is always used in `beforeDestination` and has FullStory specific behavior already.  Thus it makes for a good candidate to put a guard that benefits FullStory.
=> Limit number of suffixed props

docs/operator_suffix.md, src/operators/suffix.ts, test/operator-suffix.spec.ts
Put a ceiling on the suffix operator's `maxProps` feature.  No rush on reviewing this one, just a nice to have and will go out whenever we push a new release.
=> Limit maxProps to FullStory 5000 cardinality

src/observer.ts
This PR removes the need to carry the `attempt` parameter around with `registerRule` and the circular dependency between `registerRule` and `registerRuleWithDelay`
@van-fs please check it out and let me know what you think.
=> replace registerRuleWithDelay with a more generic sleep function

CHANGELOG.md, README.md, package-lock.json, package.json, src/operators/suffix.ts, test/operator-suffix.spec.ts
I'm finding the suffix operator's handling of undefined needs tuning:
- The large object fix is counting all properties in an object. It appears Adobe for example may have a long list of undefined values (e.g. eVars).  So we're including them in the total count; however, they'll never be sent to the destination because suffix prunes undefined values.
- I added some quick guards for conditions where we just shouldn't process at all. For example, if a property is undefined, just return null so we don't perform needless work.  Same for someone giving us a null/undefined object.
@patrick-fs WDYT
=> Adjust suffixing undefined values

rulesets/README.md, rulesets/ceddl.js, test/rules-ceddl-fullstory.spec.ts
Previously, CEDDL tests were against an example ruleset that didn't match the out-of-the-box ruleset provided for organizations which enabled the Data Layer Observer integration and toggled on the Customer Experience Digital Data Layer: 1.0 option. Now, we test against the default ruleset. This required removing and updating a number of tests since some expectations were no longer valid.
There are no behavior changes in this PR, so the package version hasn't been bumped.
/cc @patrick-fs @van-fs
=> Add CEDDL out-of-the-box ruleset; test against this ruleset

CHANGELOG.md, README.md, package.json, src/embed/init.ts, src/monitor-factory.ts, src/selector.ts, src/utils/object.ts, test/object-utils.spec.ts
IE11 doesn't support the ES2015 `String.prototype.startsWith` function.
I opted for an internal `startsWith` implementation for a couple reasons:
- I think `startsWith` reads clearer than introducing `indexOf('target', 'searchString') === 0` or `indexOf('target', 'searchString') !== 0` at the current call sites
- I don't think it makes sense for DLO to poly-fill by adding onto `String.prototype` which could impact other JavaScript on the page
Suggestions for alternative approaches definitely welcome.
=> Replace String.prototype.startsWith usage with internal implementation

package-lock.json
This PR updates the package-lock.json version to match the on in package.json
=> syncing package-lock.json version with package.json version

CHANGELOG.md, package-lock.json, package.json, src/handler.ts, test/handler.spec.ts, test/rules-adobe-fullstory.spec.ts
Within `handleData` seemed to be the most optimal place to change this behavior for a couple reasons:
- If we added empty data checking in `handleEvent`, we also would've needed to add empty data checking in `fireEvent` for `readOnLoad: true` scenarios (and we would've needed to test both `fireEvent` and `handleEvent`)
- It's possible data received in `fireEvent` or `handleEvent` could start as non-empty but eventually become empty through operator data processing -- meaning we'd still have a seam to submit empty data to the configured rule destination (e.g. `FS.event`).
Definitely open to feedback about other ways to implement this.
I opted to unit test this pretty heavily and add more of an integration test within our Adobe ruleset tests since empty `eVar` objects sparked interest in …
=> Don't handle empty data in operators or send to configured rule destination

CHANGELOG.md, package-lock.json, package.json, src/event.ts, src/handler.ts, src/monitor-factory.ts, src/monitor-shim.ts, src/monitor.ts, src/observer.ts, test/handler.spec.ts, test/monitor-factory.spec.ts, test/observer.spec.ts, test/rules-custom.spec.ts, test/shim-monitor.spec.ts, test/utils/mocha.ts
When applying selector patterns (e.g. prefix / head match) to rule sources it was previously possible for a rule to be triggered by changes to a property on the underlying source even if the property that changed didn't match the rule's selector pattern.
Example: Rule source `s[^(eVar1)]` should only care about changes to `s.eVar1`, `s.eVar10`, `s.eVar100`, etc. However, if another rule were monitoring `s[^(eVar2)]` and the value of `s.eVar2` changed the rule monitoring `s[^(eVar1)]` would've been triggered since both rules monitored the same source `s`. This change partitions eventing by rule source such that rules with different sources are triggered independently by the properties they're monitoring.
=> Prevent triggering rules with property changes that don't match selector

README.md
Following the DLO v1.12.0 release, updates the README to point to the latest version.
=> Update README to reference latest DLO version 1.12.0

src/utils/telemetry.ts, test/telemetry.spec.ts
Adds initial abstractions and a default provider implementation for collecting telemetry. The following work will build upon the changes in this PR:
- Implement "safe" telemetry wrappers which prevent telemetry collection and reporting from throwing errors
- Wire up telemetry to collect metrics (e.g. initialization duration)
- Add a console telemetry exporter which is used by default
- Enable configuring a custom telemetry provider or telemetry exporter
I haven't bumped the library version as part of these changes since these abstractions and the default provider implementation are unused and will not be included in build bundles.
=> Add telemetry abstractions and default provider implementation

CHANGELOG.md, README.md, package-lock.json, package.json, src/selector.ts, test/selector.spec.ts
This pull request allows string values to be quoted with `'` or `"` values.  To be backwards compatible, the quotes are optional.  In the code I simply look for them in string values and strip them off if they are there.  Tests were updated to try with and without quotes, as well as testing for empty string.  Empty string can be tested by doing ?(attribute='') in the selector.
=> Allowing testing of empty string for selector

src/utils/telemetry.ts, test/operator-function.spec.ts, test/telemetry.spec.ts
Adds a console telemetry exporter which will be the default telemetry exporter once telemetry collection is wired up. Builds upon work in #161.
Upcoming work:
- Implement "safe" telemetry wrappers which prevent telemetry collection and reporting from throwing errors
- Wire up telemetry to collect metrics (e.g. initialization duration)
- Enable configuring a custom telemetry provider or telemetry exporter
I haven't bumped the library version as part of these changes since this exporter is unused and will not be included in build bundles.
=> Add console telemetry exporter

CHANGELOG.md, docs/performance.md
I haven't bumped the library version since there aren't any behavior changes. This extraneous whitespace trips up precommit hooks as part of synchronizing for releases.
=> Clean up whitespace which fails release sync precommit hooks

README.md, package-lock.json, package.json, src/embed/init.impl.ts, src/observer.ts, test/observer.spec.ts
Due to the previous technique of || the value 0 would never come through.  This allows that value to come through as well as officially trying to parse string values if they contain numbers
=> Fixing logLevel bug where ERROR (0) would get dropped

CHANGELOG.md, package-lock.json, package.json, rollup.config.js, src/embed/init.impl.ts, src/handler.ts, src/monitor-shim.ts, src/monitor.ts, src/observer.ts, src/utils/telemetry.ts, test/telemetry.spec.ts
This PR uses telemetry to instrument the following:
- Overall DLO initialization time
- Time to collect configured rules from the `window` object
- Time to register all rules
- Time to handle each event (execute operator pipeline and send to configured rule destination) along with the number of operators and type of operators configured for a given event
- Count of client errors segmented by error type
- Count of rules configured for the DLO instance
=> Instrument significant timings, rule counts, and error counts

CHANGELOG.md, package-lock.json, package.json, src/handler.ts
Before this change, we're including debounce time in the measured event handling duration. By default, this debounce time is 250ms, and that debounce duration will be renewed if there are additional changes to a given rule source and path within the debounce duration. While cumulative debounce time could be interesting to measure explicitly in the future, event handling duration is intended to measure the time it takes to execute an operator pipeline -- including the final function operator call to send the transformed data to the configured rule destination. This PR narrows the scope of the event handling span to operator pipeline execution (excluding debounce time).
=> Exclude debounce time from measured event handling duration

CHANGELOG.md, README.md, package-lock.json, package.json, src/observer.ts, src/utils/telemetry.ts
This PR adds rule count as an attribute to the rule registration span telemetry type and deprecates the dedicated rule count telemetry type for removal in a future major version release. The structure and naming of `ruleCount` matches the `operatorCount` attribute on the handle event duration telemetry type.
=> Add rule count as attribute to rule registration span telemetry; deprecate rule count telemetry type

README.md
Updates README to fully reference the latest DLO version (v2). Also updates `beforeDestination` operator references to match those served by FullStory data layer integrations.
=> Fully reference latest DLO version and suggested beforeDestination operators

src/utils/telemetry.ts, test/telemetry.spec.ts
This PR prevents the DefaultTelemetryProvider from exporting or sending negative or non number values.
=> ignore time spans that are negative or not a number

package-lock.json
This PR resolves a security alert: json-schema is vulnerable to Prototype Pollution #2
https://github.com/fullstorydev/fullstory-data-layer-observer/security/dependabot/2
=> bump json-schema version from 0.2.3 to 0.4.0

test/rules-custom.spec.ts, test/utils/mocha.ts
This file tests edge cases that aren't covered by rulesets served with data layer capture integrations.
=> Support optionally running custom ruleset tests in browsers

rulesets/tealium-retail.js, test/rules-tealium-fullstory.spec.ts
- Updates Tealium ruleset rules to match rules served with data layer capture integrations.
- Adds support for optionally running Tealium ruleset tests in browsers.
=> Support optionally running Tealium ruleset tests in browsers

src/observer.ts, src/utils/logger.ts, test/observer.spec.ts
The `record` log level was originally positioned to collect stats but was never implemented. Instead, in DLO v2.0.0 [telemetry was enhanced to collect stats](https://github.com/fullstorydev/fullstory-data-layer-observer/blob/main/CHANGELOG.md#200). Since we're approaching a DLO major version bump, this PR removes the `record` log level which has always been a noop but which could be referenced by library consumers. Accordingly, it seems to make sense to treat this as a breaking change.
=> Remove record log level

src/observer.ts, src/utils/telemetry.ts
After originally rolling out telemetry, we noticed a couple things:
- Having separate rule count telemetry was resulting in an unnecessarily large volume of events since rule count could reasonably be included as metadata on rule registration timings
- Tracking 0-valued rule counts was skewing metrics for legitimate configurations
Dedicated rule count telemetry was deprecated in [v2.1.0](https://github.com/fullstorydev/fullstory-data-layer-observer/blob/main/CHANGELOG.md#210). In preparing for a major version bump, this PR removes the deprecated rule count telemetry type and its usage.
=> Remove deprecated rule count telemetry type

docs/operator_convert.md
This throws off a pre-commit hook when we sync to deploy a new CDN version.
In the future, it'd be good to match those pre-commit hook rules in the pre-commit hook rules for this repo.
=> Remove unexpected empty space in convert operator docs

rulesets/ceddl.js, test/rules-ceddl-fullstory.spec.ts
Reflects changes to default, out-of-the-box rules.
=> CEDDL digitalData.cart.item rule is no longer readOnLoad: false

test/operator-parse.spec.ts
This is causing the regular tests to not run as expected.
=> Remove .only from operator-parse.spec test

rulesets/README.md
Updates the ruleset `README`:
- Fixes broken Google ruleset reference links
- Adds GA4 reference links
=> Fix Google ruleset references / add GA4 references

test/rules-google-enhanced-ecommerce-ga4-fullstory.spec.ts
These tests were passing when running in a Node environment. However, when passing in a browser parent scope values must be explicitly passed to the test harness. See Adobe tests for an example: https://github.com/fullstorydev/fullstory-data-layer-observer/blob/main/test/rules-adobe-fullstory.spec.ts#L43-L51
=> Fix GA4 browser ruleset tests to pass parent scope values

package.json
Increases the Playwright test timeout for our `test:browser` script. I occasionally see the 3s timeout exceeded when running tests locally, and bumping the timeout seems to help. These tests are primarily run as smoke tests against new releases so the timeout duration isn't of great concern.
=> Increase Playwright test timeout

src/target.ts
There is a new object in the `FS` SDK called `dataLayer`.  As the name indicates, it is a data layer containing Fullstory-specific content (e.g. model scores).  Unfortunately, we can't observe it due to a guard in DLO.  The guard checks if the data layer is an object since many of our historical data layers were object-based.  The check `typeof FS` returns a "function" so observation fails with a `Rule Registration Error`.  Rather than make the guard too much more permissive, I'm making an exception for `FS` specifically.
I've done manual testing and can confirm registration succeeds.
=> Support FS dataLayer

docs/operator_convert.md, src/operators/convert.ts, src/utils/object.ts, test/operator-convert-nested.spec.ts
This is to add the ability for the `convert` operator to work on nested objects.  Right now it only works on one level, this adds a new property called `maxDepth` (following the pattern of the `flatten` operator), that triggers the new behavior.
=> Irv fs/convert nested
